### ISSUE TITLE
Unable to publish results to dependency-track for report generated from gradle plugin in Jenkins

### ISSUE THREAD

**Issue by adeline-chew-sp** [stevespringett/dependency-track#139]
Hi there, I'm running a report (on Jenkins) using dependency check gradle plugin and it generates the reports just fine. 
Here's my gradle setup, I'm using another job that downloads the NVD 
```
dependencyCheck {
		autoUpdate = false
		format = 'XML'
		data {
			directory = 'dependency-check-data'
		}
	}
```

However, when it tries to publish reports to dependency track (using Jenkins dependency check plugin) - it failed with no error message:
```
[DependencyCheck] Collecting Dependency-Check analysis files...
[DependencyCheck] Searching for all files in /mnt/ubuntu/workspace/dependency-check that match the pattern **/dependency-check-report.xml
[DependencyCheck] Parsing 41 files in /mnt/ubuntu/workspace/dependency-check
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/build/reports/dependency-check-report.xml with 17 unique warnings and 0 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/1/build/reports/dependency-check-report.xml with 278 unique warnings and 17 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/2/build/reports/dependency-check-report.xml with 278 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/3/build/reports/dependency-check-report.xml with 278 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/4/build/reports/dependency-check-report.xml with 278 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/5/build/reports/dependency-check-report.xml with 278 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/6/build/reports/dependency-check-report.xml with 278 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/7/build/reports/dependency-check-report.xml with 278 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/8/build/reports/dependency-check-report.xml with 278 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/9/build/reports/dependency-check-report.xml with 278 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/10/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/11/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/12/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/13/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/14/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/15/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/16/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/17/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/18/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/19/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/20/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/21/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/22/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/23/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/24/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/25/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/26/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/27/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/28/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/29/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/30/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/31/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/32/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/33/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/34/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/35/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/36/build/reports/dependency-check-report.xml with 279 unique warnings and 278 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/37/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/38/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/39/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyCheck] Successfully parsed file /mnt/ubuntu/workspace/dependency-check/40/build/reports/dependency-check-report.xml with 279 unique warnings and 279 duplicates.
[DependencyTrack] Publishing artifact to Dependency-Track
Build step 'Publish results to Dependency-Track' changed build result to FAILURE
```

Please assist.

**Comment by adeline-chew-sp** [comment]
I logged it and the log appears to be empty

**Comment by adeline-chew-sp** [comment]
Let me investigate more and get back, thank you for the prompt response

**Comment by adeline-chew-sp** [comment]
Received a different error now, I think it's permission (the jenkins slave doesn't have permission to publish to DependencyTrack)
```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at hudson.tasks.Publisher.getDescriptor(Publisher.java:122)
	at hudson.tasks.Recorder.getDescriptor(Recorder.java:51)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.getDescriptor(DependencyTrackPublisher.java:205)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.upload(DependencyTrackPublisher.java:167)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.access$100(DependencyTrackPublisher.java:56)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher$1.call(DependencyTrackPublisher.java:120)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher$1.call(DependencyTrackPublisher.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to ec2-instance1 (i-xxxxxxxxxx)(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.perform(DependencyTrackPublisher.java:118)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Publish results to Dependency-Track' marked build as failure
```

**Comment by stevespringett** [comment]
Ensure that the team containing the API Key you're using has the SCAN_UPLOAD and VIEW_PORTFOLIO permission. Initially, the VIEW_PORTFOLIO permission was not assigned to the 'automation' team by default. This was corrected in a later release, but for existing users, you'll just need to add the permission.

**Comment by adeline-chew-sp** [comment]
Great! Thank you!

**Comment by adeline-chew-sp** [comment]
This was an actual issue - reported here https://issues.jenkins-ci.org/browse/JENKINS-51053?workflowName=JNJira+%2B+In-Review&stepId=4
