### ISSUE TITLE
Publish result to Dependency-Track fail from Jenkins

### ISSUE THREAD

**Issue by johnsonqu** [stevespringett/dependency-track#142]
Pls check the Jenkins job console output as below: 

[DependencyTrack] Publishing artifact to Dependency-Track
ERROR: Build step failed with exception
java.lang.NullPointerException
	at hudson.tasks.Publisher.getDescriptor(Publisher.java:122)
	at hudson.tasks.Recorder.getDescriptor(Recorder.java:51)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.getDescriptor(DependencyTrackPublisher.java:205)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.upload(DependencyTrackPublisher.java:167)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.access$100(DependencyTrackPublisher.java:56)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher$1.call(DependencyTrackPublisher.java:120)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher$1.call(DependencyTrackPublisher.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:181)
	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to JNLP4-connect connection from 10.71.130.77/10.71.130.77:35432(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1554)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:281)
	at hudson.remoting.Channel.call(Channel.java:839)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.perform(DependencyTrackPublisher.java:118)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Build step 'Publish results to Dependency-Track' marked build as failure

**Comment by stevespringett** [comment]
Ensure the VIEW_PORTFOLIO and SCAN_UPLOAD permissions are assigned to the API key being used and that the URL to Dependency-Track does not have a trailing slash. Future versions of the Jenkins plugin will be a bit more graceful about the tailing slash. If you continue to experience issues, create an issue specific to the Jenkins plugin here: https://issues.jenkins-ci.org/
