### ISSUE TITLE
Error when delete not empty project in 3.1

### ISSUE THREAD

**Issue by stboiss** [stevespringett/dependency-track#151]
when I delete a not empty project, i have this error:
```
2018-05-15 10:01:54,261 [] WARN [org.eclipse.jetty.server.HttpChannel] /api/v1/project/50b9b927-c92e-469f-bd7d-4dfe968fd810
javax.servlet.ServletException: javax.jdo.JDODataStoreException: Exception thrown flushing changes to datastore
NestedThrowables:
java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`dtrack`.`DEPENDENCYMETRICS`, CONSTRAINT `DEPENDENCYMETRICS_FK2` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`ID`))
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:432)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at alpine.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:223)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)

```

**Comment by stevespringett** [comment]
This issue should be resolved. I've tested with a large project and works as designed. Please reopen if it's still an issue.

**Comment by stboiss** [comment]
@stevespringett , it's OK
