### ISSUE TITLE
uuid column

### ISSUE THREAD

**Issue by Pamir** [stevespringett/dependency-track#61]
in 3.0-dev branch

After enhancing with datanucleus tomcat gets the exception below

SEVERE: Error thrown executing ALTER TABLE LICENSE ADD COLUMN UUID VARCHAR(36) NOT NULL : NULL not allowed for column "UUID"; SQL statement:
ALTER TABLE LICENSE ADD COLUMN UUID VARCHAR(36) NOT NULL [23502-176]
org.h2.jdbc.JdbcSQLException: NULL not allowed for column "UUID"; SQL statement:
ALTER TABLE LICENSE ADD COLUMN UUID VARCHAR(36) NOT NULL [23502-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.table.Column.validateConvertUpdateSequence(Column.java:308)
        at org.h2.table.Table.validateConvertUpdateSequence(Table.java:726)
        at org.h2.command.dml.Insert.addRow(Insert.java:196)
        at org.h2.command.dml.Select.queryFlat(Select.java:545)
        at org.h2.command.dml.Select.queryWithoutCache(Select.java:646)
        at org.h2.command.dml.Query.query(Query.java:323)
        at org.h2.command.dml.Insert.insertRows(Insert.java:168)
        at org.h2.command.dml.Insert.update(Insert.java:115)
        at org.h2.command.ddl.CreateTable.update(CreateTable.java:184)
        at org.h2.command.ddl.AlterTableAlterColumn.execute(AlterTableAlterColumn.java:448)
        at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:348)
        at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:226)
        at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:158)
        at org.h2.command.CommandContainer.update(CommandContainer.java:79)
        at org.h2.command.Command.executeUpdate(Command.java:254)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
        at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
        at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
        at org.datanucleus.store.rdbms.table.AbstractTable.executeDdlStatement(AbstractTable.java:879)
        at org.datanucleus.store.rdbms.table.AbstractTable.executeDdlStatementList(AbstractTable.java:830)
        at org.datanucleus.store.rdbms.table.TableImpl.validateColumns(TableImpl.java:257)
        at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.performTablesValidation(RDBMSStoreManager.java:3398)
        at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:2896)
        at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:119)
        at org.datanucleus.store.rdbms.RDBMSStoreManager.createSchemaForClasses(RDBMSStoreManager.java:3877)
        at org.datanucleus.store.schema.SchemaTool.createSchemaForClasses(SchemaTool.java:499)
        at org.datanucleus.PersistenceNucleusContextImpl.initialiseSchema(PersistenceNucleusContextImpl.java:953)
        at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:481)
        at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:842)
        at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:333)
        at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:212)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by Pamir** [comment]
Hi Steve,

Yes it is up to date. I fetched the latest commits. BTW it could be a windows issue. I'll try it on Linux and tell you.

**Comment by stevespringett** [comment]
Closing due to inactivity. If issue persists on the master branch, reopen the ticket.
