### ISSUE TITLE
Publishing results using Jenkins 

### ISSUE THREAD

**Issue by Idanatcox** [stevespringett/dependency-track#71]
Thanks for your work!
I'm trying to use Jenkins plugin to publish the analysis results to Dependecy-Tracker.
I tried to publish against both 3.0 and 2.0 branches of depedency-tracker with no success. The build is not running on master but on a linux node
I understand it's still heavy dev but just wondering if I'm doing something wrong.
The compilation of "master" branch of the jenkins plugin fails with the exception below.

Jenkins version: 2.46.3
Jenkins plugin: 2.1.1

`[DependencyTrack] Publishing Dependency-Check results to Dependency-Track
ERROR: Step ‘Publish results to OWASP Dependency-Track’ aborted due to exception: 
java.io.NotSerializableException: java.io.PrintStream
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:190)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:199)
Caused: java.io.IOException: Unable to serialize org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher$1@36e8b03e
	at hudson.remoting.UserRequest.serialize(UserRequest.java:201)
	at hudson.remoting.UserRequest.<init>(UserRequest.java:64)
	at hudson.remoting.Channel.call(Channel.java:828)
	at org.jenkinsci.plugins.DependencyCheck.DependencyTrackPublisher.perform(DependencyTrackPublisher.java:108)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)`

`[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/a1jenkinsbuild/dependency-check-plugin/src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java:[143,45] error: incompatible types: Settings cannot be converted to Mode
[ERROR] /home/a1jenkinsbuild/dependency-check-plugin/src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java:[145,21] error: no suitable constructor found for Engine(Settings)
[ERROR]     constructor Engine.Engine(Mode) is not applicable
      (argument mismatch; Settings cannot be converted to Mode)
    constructor Engine.Engine(ClassLoader) is not applicable
      (argument mismatch; Settings cannot be converted to ClassLoader)
/home/a1jenkinsbuild/dependency-check-plugin/src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java:[202,19] error: constructor Settings in class Settings cannot be applied to given types;
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.568s
[INFO] Finished at: Sat Sep 16 13:40:28 EDT 2017
[INFO] Final Memory: 36M/72M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project dependency-check-jenkins-plugin: Compilation failure: Compilation failure:
[ERROR] /home/a1jenkinsbuild/dependency-check-plugin/src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java:[143,45] error: incompatible types: Settings cannot be converted to Mode
[ERROR] /home/a1jenkinsbuild/dependency-check-plugin/src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java:[145,21] error: no suitable constructor found for Engine(Settings)
[ERROR] constructor Engine.Engine(Mode) is not applicable
[ERROR] (argument mismatch; Settings cannot be converted to Mode)
[ERROR] constructor Engine.Engine(ClassLoader) is not applicable
[ERROR] (argument mismatch; Settings cannot be converted to ClassLoader)
[ERROR] /home/a1jenkinsbuild/dependency-check-plugin/src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java:[202,19] error: constructor Settings in class Settings cannot be applied to given types;`

**Comment by stevespringett** [comment]
So, you're using the official released version of the Jenkins 2.1.1 plugin, correct?

Is this a freestyle, maven, or pipeline build?

And for Dependency-Track you're compiling the 3.0-dev branch and running that correct?

**Comment by Idanatcox** [comment]
Yes, it's a freestyle job using plugin version 2.1.1 (because the latest plugin code compilation fails with the exception above) against Dependency-Track 3.0-dev compiled code, I've tried deleting ~/.dependency-track folder and the docker image as well with no success (it ran successfully just failed on the same place)

**Comment by stevespringett** [comment]
Corrected in https://github.com/jenkinsci/dependency-check-plugin/commit/09fc0ba02324c718a216068a2bdfd28ce3f43156

Closing
