### ISSUE TITLE
File not found exception in logs

### ISSUE THREAD

**Issue by adunkey** [stevespringett/dependency-track#95]
When importing a scan results via the dependency check Jenkins plugin, everything seems fine in UI but I get this exception in the dependency-track.log:

2018-02-22 04:41:24,593 [] INFO [org.owasp.dependencycheck.Engine] Analysis Complete (3 seconds)
2018-02-22 04:41:24,593 [] ERROR [org.owasp.dependencytrack.tasks.DependencyCheckTask] An error occurred executing Dependency-Check scan agent: org.owasp.dependencycheck.exception.ScanAgentException: One or more exceptions occurred during analysis; please see the debug log for more details.
2018-02-22 04:41:24,593 [] INFO [org.owasp.dependencytrack.tasks.DependencyCheckTask] Dependency-Check analysis complete
2018-02-22 04:41:24,593 [] INFO [org.owasp.dependencytrack.tasks.DependencyCheckTask] Processing Dependency-Check analysis results
2018-02-22 04:41:24,738 [] ERROR [org.owasp.dependencytrack.tasks.DependencyCheckTask] An error occurred while parsing Dependency-Check report
org.owasp.dependencytrack.exception.ParseException: javax.xml.stream.XMLStreamException: java.io.FileNotFoundException: /root/.dependency-track/dependency-check/reports/dependency-check-report.xml (No such file or directory)
        at org.owasp.dependencytrack.parser.dependencycheck.DependencyCheckParser.parse(DependencyCheckParser.java:82)
        at org.owasp.dependencytrack.parser.dependencycheck.DependencyCheckParser.parse(DependencyCheckParser.java:47)
        at org.owasp.dependencytrack.tasks.DependencyCheckTask.processResults(DependencyCheckTask.java:156)
        at org.owasp.dependencytrack.tasks.DependencyCheckTask.analyze(DependencyCheckTask.java:147)
        at org.owasp.dependencytrack.tasks.DependencyCheckTask.performAnalysis(DependencyCheckTask.java:104)
        at org.owasp.dependencytrack.tasks.DependencyCheckTask.inform(DependencyCheckTask.java:70)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: java.io.FileNotFoundException: /root/.dependency-track/dependency-check/reports/dependency-check-report.xml (No such file or directory)
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:212)
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.<init>(XMLStreamReaderImpl.java:184)
        at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:143)
        at org.owasp.dependencytrack.parser.dependencycheck.DependencyCheckParser.parse(DependencyCheckParser.java:77)
        ... 11 common frames omitted
Caused by: java.io.FileNotFoundException: /root/.dependency-track/dependency-check/reports/dependency-check-report.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDocumentEntity(XMLEntityManager.java:1255)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.setInputSource(XMLDocumentScannerImpl.java:253)
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:199)
        ... 14 common frames omitted
2018-02-22 04:41:24,740 [] INFO [org.owasp.dependencytrack.tasks.DependencyCheckTask] Processing complete
2018-02-22 05:02:38,947 [] INFO [org.owasp.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on portfolio
2018-02-22 05:02:38,949 [] INFO [org.owasp.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: c09d6163-06ea-439f-a7b6-6eb2eb5b6ffb

looking in  /root/.dependency-track/ there is no dependency-check folder.

Thanks,

AD

**Comment by stevespringett** [comment]
Once 3.0.1 is released (within the next few days), go ahead and follow the instructions here: Refer to https://github.com/stevespringett/dependency-track/blob/3.0.x/upgrade
