### ISSUE TITLE
Proxy environment variables support

### ISSUE THREAD

**Issue by MelvinKool** [stevespringett/dependency-track#99]
It would be nice when the project uses the environment variable http_proxy, https_proxy and no_proxy.
When running docker for example, this makes it much easier to deploy docker containers.

**Comment by stevespringett** [comment]
@MelvinKool If you set the https_proxy or http_proxy variable, the system should honor it. I have no way of testing, but feel free to reopen ticket if you run into problems.

**Comment by MelvinKool** [comment]
@stevespringett That was quick!  You might also want to check the uppercase version HTTPS_PROXY and HTTP_PROXY.
Both upper case and lower case are valid.

**Comment by MelvinKool** [comment]
Unfortunately, it failed.
I had both the lower and upper case version of the proxy environment variables set.
I'm sure they are used and work in other docker containers.
Do you see a possible cause, by looking at the following logs?

`2018-03-02 08:45:51,484 [] INFO [alpine.Config] --------------------------------------------------------------------------------
2018-03-02 08:45:51,485 [] INFO [alpine.Config] Initializing Configuration
2018-03-02 08:45:51,485 [] INFO [alpine.Config] System property alpine.application.properties not specified
2018-03-02 08:45:51,485 [] INFO [alpine.Config] Loading application.properties from classpath
2018-03-02 08:45:51,488 [] INFO [alpine.Config] --------------------------------------------------------------------------------
2018-03-02 08:45:51,489 [] INFO [alpine.Config] Application: Dependency-Track
2018-03-02 08:45:51,489 [] INFO [alpine.Config] Version:     3.0.0-SNAPSHOT
2018-03-02 08:45:51,489 [] INFO [alpine.Config] Built-on:    2018-03-01 20:28:59
2018-03-02 08:45:51,489 [] INFO [alpine.Config] --------------------------------------------------------------------------------
2018-03-02 08:45:51,489 [] INFO [alpine.Config] Framework:   Alpine
2018-03-02 08:45:51,489 [] INFO [alpine.Config] Version :    1.0.0
2018-03-02 08:45:51,490 [] INFO [alpine.Config] Built-on:    2018-02-28 00:19:40
2018-03-02 08:45:51,492 [] INFO [alpine.Config] --------------------------------------------------------------------------------
2018-03-02 08:45:51,696 [] INFO [alpine.persistence.PersistenceManagerFactory] Initializing persistence framework
2018-03-02 08:45:54,472 [] INFO [org.owasp.dependencytrack.persistence.CweImporter] Syncing CWEs with datastore
2018-03-02 08:45:56,832 [] INFO [org.owasp.dependencytrack.persistence.CweImporter] CWE sync complete
2018-03-02 08:45:56,920 [] INFO [alpine.AlpineServlet] Starting Dependency-Track
2018-03-02 08:46:03,352 [] INFO [org.owasp.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on portfolio
2018-03-02 08:46:03,429 [] INFO [org.owasp.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on vulnerability database
2018-03-02 08:46:03,427 [] INFO [org.owasp.dependencytrack.tasks.NspMirrorTask] Starting NSP mirroring task
2018-03-02 08:46:03,439 [] INFO [org.owasp.dependencytrack.tasks.NspMirrorTask] Retrieving NSP advisories at Fri Mar 02 08:46:03 GMT 2018
2018-03-02 08:46:03,441 [] ERROR [alpine.Config] Error parsing number from property: alpine.http.proxy.port
2018-03-02 08:46:03,783 [] INFO [org.owasp.dependencytrack.tasks.NspMirrorTask] Retrieving NSP advisories from https://api.nodesecurity.io/advisories
2018-03-02 08:46:53,353 [] INFO [org.owasp.dependencytrack.tasks.VulnDbSyncTask] Starting VulnDB mirror synchronization task
2018-03-02 08:46:53,354 [] INFO [org.owasp.dependencytrack.tasks.VulnDbSyncTask] VulnDB mirror directory does not exist. Skipping.
2018-03-02 08:46:53,361 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Starting NIST mirroring task
2018-03-02 08:46:53,361 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Downloading files at Fri Mar 02 08:46:53 GMT 2018
2018-03-02 08:46:53,363 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Initiating download of https://nvd.nist.gov/download/nvdcve-2002.xml.gz
2018-03-02 08:48:11,090 [] ERROR [org.owasp.dependencytrack.tasks.NspMirrorTask] An error occurred while retrieving NSP advisory
com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.HttpHostConnectException: Connect to api.nodesecurity.io:443 [api.nodesecurity.io/147.75.199.165] failed: Operation timed out (Connection timed out)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
	at org.owasp.dependencytrack.tasks.NspMirrorTask.getAdvisories(NspMirrorTask.java:96)
	at org.owasp.dependencytrack.tasks.NspMirrorTask.inform(NspMirrorTask.java:72)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.nodesecurity.io:443 [api.nodesecurity.io/147.75.199.165] failed: Operation timed out (Connection timed out)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
	... 9 common frames omitted
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 20 common frames omitted
2018-03-02 08:48:11,090 [] INFO [org.owasp.dependencytrack.tasks.NspMirrorTask] NSP mirroring complete
2018-03-02 08:49:00,624 [] ERROR [org.owasp.dependencytrack.tasks.NistMirrorTask] Download failed : Connect to nvd.nist.gov:443 [nvd.nist.gov/129.6.13.177] failed: Operation timed out (Connection timed out)
2018-03-02 08:49:00,624 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.xml.gz
2018-03-02 08:51:07,856 [] ERROR [org.owasp.dependencytrack.tasks.NistMirrorTask] Download failed : Connect to nvd.nist.gov:443 [nvd.nist.gov/129.6.13.177] failed: Operation timed out (Connection timed out)
2018-03-02 08:51:07,856 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Initiating download of https://static.nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2002.json.gz
2018-03-02 08:53:15,088 [] ERROR [org.owasp.dependencytrack.tasks.NistMirrorTask] Download failed : Connect to static.nvd.nist.gov:443 [static.nvd.nist.gov/129.6.13.177] failed: Operation timed out (Connection timed out)
2018-03-02 08:53:15,088 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Initiating download of https://nvd.nist.gov/download/nvdcve-2003.xml.gz
2018-03-02 08:55:22,320 [] ERROR [org.owasp.dependencytrack.tasks.NistMirrorTask] Download failed : Connect to nvd.nist.gov:443 [nvd.nist.gov/129.6.13.177] failed: Operation timed out (Connection timed out)
2018-03-02 08:55:22,320 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2003.xml.gz
2018-03-02 08:57:29,552 [] ERROR [org.owasp.dependencytrack.tasks.NistMirrorTask] Download failed : Connect to nvd.nist.gov:443 [nvd.nist.gov/129.6.13.177] failed: Operation timed out (Connection timed out)
2018-03-02 08:57:29,552 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Initiating download of https://static.nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2003.json.gz
2018-03-02 08:59:36,784 [] ERROR [org.owasp.dependencytrack.tasks.NistMirrorTask] Download failed : Connect to static.nvd.nist.gov:443 [static.nvd.nist.gov/129.6.13.177] failed: Operation timed out (Connection timed out)
2018-03-02 08:59:36,784 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Initiating download of https://nvd.nist.gov/download/nvdcve-2004.xml.gz
2018-03-02 09:01:44,016 [] ERROR [org.owasp.dependencytrack.tasks.NistMirrorTask] Download failed : Connect to nvd.nist.gov:443 [nvd.nist.gov/129.6.13.177] failed: Operation timed out (Connection timed out)
2018-03-02 09:01:44,016 [] INFO [org.owasp.dependencytrack.tasks.NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2004.xml.gz
`

**Comment by stevespringett** [comment]
Lower, upper, and mixed case of the vars should work now. 

Regarding the timeout issue, likely a proxy preventing the request from going through. 

I also found a flaw in the proxy credentials logic. So if the proxy required authentication, it would not work. This has also been fixed.

Between these two fixes, if you still experience the issue, it would be really helpful if you could set `org.apache.http` to DEBUG in `logback.xml` and restart the application. This should write all debug info (including headers and connections) to the log. If the log contains sensitive information, feel free to PM me on the Slack channel or send the log to steve.springett@owasp.org.

**Comment by stevespringett** [comment]
Closing. Verified that current proxy functionality works.
